import os
from datetime import datetime
from fpdf import FPDF


class PDFReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(232, 117, 26)
        self.cell(0, 8, "OSINT FOX - Intelligence Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(232, 117, 26)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def sub_category(self, text):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(200, 200, 200)
        self.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def key_value(self, key, value):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(180, 180, 200)
        kw = self.get_string_width(key) + 4
        self.cell(kw, 7, key)
        self.set_text_color(220, 220, 220)
        self.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(200, 200, 200)
        self.multi_cell(0, 6, text)
        self.ln(2)


def export_to_pdf(results_flat, filepath, target=None):
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(232, 117, 26)
    pdf.cell(0, 15, "OSINT FOX", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(200, 200, 200)
    pdf.cell(0, 8, "Open Source Intelligence Report", align="C", new_x="LMARGIN", new_y="NEXT")
    if target:
        pdf.cell(0, 8, f"Target: {target}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    current_section = ""
    for key, value in results_flat:
        if not key and not value:
            pdf.ln(3)
            continue
        if key.startswith("[") and key.endswith("]"):
            current_section = key.strip("[]")
            pdf.sub_category(current_section)
        elif key.startswith("  "):
            pdf.key_value(key.strip(), value)
        else:
            if key in ("Scan Time", "Module", "Description"):
                pdf.key_value(key, value)

    pdf.output(filepath)
    return filepath


def export_to_txt(results_flat, filepath, target=None):
    lines = []
    lines.append("=" * 60)
    lines.append("                    OSINT FOX")
    lines.append("          Open Source Intelligence Report")
    lines.append("=" * 60)
    lines.append("")
    if target:
        lines.append(f"  Target: {target}")
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    for key, value in results_flat:
        if not key and not value:
            lines.append("")
            continue
        if key.startswith("[") and key.endswith("]"):
            section = key.strip("[]")
            lines.append(f"\n{'─' * 50}")
            lines.append(f"  {section}")
            lines.append(f"{'─' * 50}")
        elif key.startswith("  "):
            lines.append(f"    {key.strip()}: {value}")
        else:
            lines.append(f"  {key}: {value}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("  Report generated by OSINT FOX")
    lines.append("=" * 60)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filepath
